### ISSUE TITLE
Model docblocks

### ISSUE THREAD

**Issue by krzysztofrewak** [blumilksoftware/meetup#51]
All models should be described with proper docblocks according to their properties/migrations.

For example, `src/Models/Meetup` should be defined as follows:
```php
/**
 * @property int $id
 * @property int $userId
 * @property User $user
 * @property int $organizationId
 * @property Organization $organization
 * @property int $speakerId
 * @property Speaker $speaker
 * @property string $title
 * @property string $description
 * @property string $date
 * @property string $place
 * @property string $language
 * @property Carbon $createdAt
 * @property Carbon $updatedAt
 */
class Meetup extends Model
{
```

With this approach you'll be able to use full potential of your IDE.

**Comment by MrHDOLEK** [comment]
@krzysztofrewak 
I configured the package and it generated most of it correctly with the minimum amount of garbage

**Comment by krzysztofrewak** [comment]
You should reconsider leaving this package in the project. 

a) according to code review, you're going to manually change some of these docblocks. Running this library again would probably remove your changes.
b) it's a development dependency only; when someone will add this library to his project, it won't be available anyway.
